
	<main class="container">
		<div class="slider">
			<div><img src="assets/img/slider-01.jpg" alt="Table seen from the top with drinks and plates with food"></div>
			<div><img src="assets/img/slider-02.jpg" alt="Zoom on a plate seen from the top and red chilli"></div>
			<div><img src="assets/img/slider-03.jpg" alt="Table seen from the top with drinks and plates with food"></div>
		</div>
		<section class="intro">
			<h1>Welcome to Freshly Restaurant</h1>
			<img src="assets/img/location.jpg" alt="view of the main dining room" class="intro-img">
			<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Voluptas sunt veritatis ipsam ipsa saepe unde possimus dicta accusantium nulla sequi praesentium commodi repudiandae, fugiat aperiam reiciendis impedit eius aspernatur at dolore placeat quae maxime laudantium optio sapiente! Architecto sequi totam qui illo doloribus nisi cupiditate perspiciatis culpa quam recusandae facere tempore necessitatibus expedita iusto facilis, quis nihil id dignissimos ex corporis minima sit. Eos deserunt maxime at animi obcaecati error rem numquam ullam vitae hic ducimus labore, in, iure nostrum!</p>
			<p>Soluta corporis est explicabo magni ducimus praesentium dignissimos hic laudantium accusantium maxime animi illum expedita sunt illo, eveniet voluptas reprehenderit quia, ipsam velit deserunt doloribus fugit iusto! Odit natus officia facere quae sunt eos unde repellat similique fugiat consectetur sint et qui, quod reiciendis perferendis. Corporis harum molestias doloribus, eaque est, quas. Amet doloribus aperiam voluptatem ad nemo minus voluptas ratione dolores in cumque dolore eius nostrum ipsa deleniti minima modi, officia odit temporibus velit excepturi, eligendi odio qui facere obcaecati.</p>
		</section>
		<section class="menu">
			<h2>Special menus</h2>
			<article>
				<h3>Meat menu</h3>
				<figure>
					<img src="assets/img/meat-menu.jpg" alt="plate with red meat">
					<figcaption>17 $<br>
						<span>soft drinks and desert included</span>
						<span>+ taxes</span>
					</figcaption>
				</figure>
				<ul>
					<li><i class="fas fa-star"></i>Lorem ipsum dolor sit.</li>
					<li><i class="fas fa-star"></i>Dolorem est fuga possimus.</li>
					<li><i class="fas fa-star"></i>Iste aperiam facere reprerit.</li>
					<li><i class="fas fa-star"></i>Amet consectur aperiam iusto.</li>
					<li><i class="fas fa-star"></i>Ipsa autem accusam ducimus.</li>
				</ul>
				<a href="menus.html" class="details"><img src="assets/img/fork-knife.svg" alt="">See more</a>
			</article>
			<article>
				<h3>Fish menu</h3>
				<figure>
					<img src="img/fish-menu.jpg" alt="Plate with shrimps and rice">
					<figcaption>19 $<br>
						<span>soft drinks and desert included</span>
						<span>+ taxes</span>
					</figcaption>
				</figure>
				<ul>
					<li><i class="fas fa-star"></i>Lorem ipsum libero consectur.</li>
					<li><i class="fas fa-star"></i>Quas aperiam pariatur.</li>
					<li><i class="fas fa-star"></i>Minus dolorum obcaecati vero.</li>
					<li><i class="fas fa-star"></i>Maxime nihil deleniti commodi.</li>
					<li><i class="fas fa-star"></i>Soluta vitae odio nesciunt.</li>
				</ul>
				<a href="menus.html" class="details"><img src="img/fork-knife.svg" alt="">See more</a>
			</article>
			<article>
				<h3>Vegetarian menu</h3>
				<figure>
					<img src="img/vegetarian-menu.jpg" alt="colorfull vegetarian plate">
					<figcaption>18 $<br>
						<span>soft drinks and desert included</span>
						<span>+ taxes</span>
					</figcaption>
				</figure>
				<ul>
					<li><i class="fas fa-star"></i>Lorem ipsum consectetur.</li>
					<li><i class="fas fa-star"></i>Expedita pariatur voluptas.</li>
					<li><i class="fas fa-star"></i>Incidunt perferendis delectus.</li>
					<li><i class="fas fa-star"></i>Voluptabus deserut nostrum.</li>
					<li><i class="fas fa-star"></i>Iste assuma laboriosam numq.</li>
				</ul>
				<a href="menus.html" class="details"><img src="img/fork-knife.svg" alt="">See more</a>
			</article>
		</section>
	</main>
	
	<footer>
		<div class="container">
			<div class="flex">
				<aside>
					<h4>Opening hours</h4>
					<table>
						<?php foreach($open as $items):?>
						<tr>
							<td><?= htmlspecialchars($items['days']);?></td>
							<td><?= htmlspecialchars($items['hours']);?></td>
						</tr>
						<?php endforeach;?>
					</table>
				</aside>
				<aside>
					<h4>Contact</h4>
					<address>
						<p>13 Christopher Street<br>
							New York,<br>
							NY 10014-3543</p>
						<p>+01 2000 800 9999</p>
					</address>
				</aside>
				<aside>
					<h4>Social networks</h4>
					<div class="reseaux">
						<a href="#" class="fab fa-facebook-f"></a>
						<a href="#" class="fab fa-instagram"></a>
						<a href="#" class="fab fa-pinterest-p"></a>
					</div>
				</aside>
			</div> <!-- end of .flex -->
			<div class="footer">
				<p><a rel="license" href="https://3wa.fr/propriete-materiel-pedagogique/"><img alt="Propriété de la 3W Academy" src="https://3wa.fr/wp-content/themes/3wa2015/img/logos/big.png"></a></p><br>
				<span>Cet exercice</span> de <a href="https://3wa.fr">3W Academy</a> est mis à disposition <a rel="license" href="https://3wa.fr/propriete-materiel-pedagogique/">pour l'usage personnel des étudiants. Pas de Rediffusion - Attribution - Pas d'Utilisation Commerciale - Pas de Modification - International</a>.<br>
				Les autorisations au-delà du champ de cette licence peuvent être obtenues auprès de <a href="mailto:contact@3wa.fr" rel="cc:morePermissions">contact@3wa.fr</a>. Les maquettes ont été réalisées par <a href="https://www.cath2nos.com">Catherine Denos</a>.
			</div> <!-- end of .footer -->
		</div> <!-- end of .container -->
	</footer>
