<main>
	<div class="container">
			<p class="logo">
				<img src="<?=$this->logo['content'] ?>" alt="Logo for Freshly Restaurant">
				<strong>Freshly Restaurant</strong>
		
			</p>
		</div>
	<form method="post">
		<p>
			<label for='login'>login</label>
			<input type="text" name="login" id="login">
		</p>
		<p>
			<label for='password'>password</label>
			<input type="password" name="password" id="password">
		</p>
		<input type="submit" name="Ajouter" value="Se connecter"/>
		<!--<button>Se connecter</button>-->
		
	</form>
</main>