
  
  <h2>Gestion de la Configuration</h2>
  
  <p>
  <a class="btn-add" href="index.php?page=Ajouter"><i class="fas fa-plus"></i>Ajouter du contenu</a>
  </p>
  <table> <!--tableau config-->
 <tr>
   <th>Name</th>
   <th>Content</th>
   <th>Modifier</th>
   <th>Supprimer</th>
 </tr>
 
 
    		<?php foreach($config as $configs): ?>
		
		 <tr class="bg-standar">
		   
	    
	     <td><?= htmlspecialchars($configs['name']) ?></td>
	     <td><?= htmlspecialchars($configs['content']) ?></td>
	     <td><a href=index.php?page=modifier&id=<?=$configs['id'] ?>><i class="fas fa-pen-nib btn-modify"></i></a></td>
       <td><a class="confirmButton" data-url=index.php?page=supprimer&id=<?=$configs['id'] ?>><i class="fas fa-trash-alt btn-error"></i></a></td>
	    </tr>
		
		<?php endforeach; ?>
  </table>
  
  
  
