
	<section>
    <h2>Bienvenu sur la page de gestion de votre site</h2>
    <p>vous avez la possibilité de modifier les éléments d'affichage de votre interface,
    et de voir les différentes réservations de vos clients.</p>
    </section>
    <section>
    <h2>Les réservation de la semaine</h2>
    <li class="btn-prev"><a ><i class="fas fa-backward"></i></a></li>
    <li class="btn-next"><a ><i class="fas fa-forward"></i></a></li>
    <table>
        <tr>
            <th>Client</th>
            <th>Jour</th>
            <th>Heure</th>
            <th>Place</th>
            <th>Demande</th>
            <th colspan="2">Traiter la reservation</th>
        </tr>
        <tr>
            <th>Client</th>
            <th>Jour</th>
            <th>Heure</th>
            <th>Place</th>
            <th>Demande</th>
            <th><i class="fas fa-check-circle btn-success"></i></th>
            <th><i class="fas fa-times-circle btn-error"></i></th>
        </tr>
    </table>
    </section>
    

