
<form method="POST">
	<p>
		<label for='email'>Votre email</label>
		<input type="text" name="email">
	</p>
	
	<p>
		<label for='pw'>Votre mot de passe</label>
		<input type="password" name="pw">
	</p>
	
	<p>
		<label for='lastname'>Votre nom</label>
		<input type="text" name="lastname">
	</p>
	
	<p>
		<label for='firstname'>Votre prénom</label>
		<input type="text" name="firstname">
	</p>
	
	<p>
		<label for='phone'>N° de Téléphone</label>
		<input type="text" name="phone">
	</p>
	
	<button type="submit">Inscription</button>
	
</form>