<!doctype html>
<html lang="fr">
<head>
	
	
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<meta name="description" content="Freshly Restaurant, your new favourite restaurant !">
	<title>Freshly Restaurant - Home</title>
	<link rel="icon" href="favicon.png">
	<link href="https://fonts.googleapis.com/css?family=Athiti:500|Merienda:400,700&display=swap" rel="stylesheet">
	<link rel="stylesheet" href="assets/css/slick.css">
	<link rel="stylesheet" href="assets/css/slick-theme.css">
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.0/css/fontawesome.min.css">
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.0/css/brands.min.css">
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.0/css/solid.min.css">
	<link rel="stylesheet" href="assets/css/style.css">
	
</head>
<body>
<header>
	<nav class="navbar navbar-expand-lg navbar navbar-dark bg-dark">
    <div class="container-fluid">
		<ul>	
		<li><a href="<?=(isset($_SESSION['admin']))?'index.php?page=Dashboard':'index.php?page=Admin'?>"><i class="fas fa-pen-nib"></i>Administration</a></li>
		
			<?php if(isset($_SESSION['admin'])):  ?>
		
			<li><a href="index.php?page=deco"><i class="fas fa-sign-out-alt"></i>Deconnexion</a></li>
			<li><a href="index.php">Accueil</a></li>
			<?php endif; ?>
		</ul>	
	</div>		
	</nav>
</header>
<main>
	<?php if(isset($_SESSION['admin'])):  ?>
	<div class="administration">
    <nav >
		<ul class="leftmenu">
			<li><a>Gestions des catégories de plats</a></li>
			<li><a>Gestions des plats</a></li>
			<li><a>Gestion du slider</a></li>
			<li><a>Gestion des horaires</a></li>
			<li><a>Gestion des réservations</a></li>
		</ul>
	</nav>	  
	<?php endif; ?>
<!-- code principal de la page -->
	<?php include $template ?>
</div>
</main>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.min.js" integrity="sha384-nsg8ua9HAw1y0W1btsyWgBklPnCUAFLuTMS2G72MMONqmOymq585AcH49TLBQObG" crossorigin="anonymous"></script>
<!-- Charger la bibliothèque de base de jQuery -->
	<script src="https://code.jquery.com/jquery-3.5.1.min.js" integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>
	<!-- Charger le script du plugin -->
	<script src="assets/js/slick.min.js"></script>
	<!-- Indiquer sur quel élément de la page on applique le plugin -->
	<script>
		$(document).ready(function () {
			$('.slider').slick({
				dots: true
			});
		});
	</script>
	
<script src=".js"></script>	
</body>
</html>	