<!doctype html>
<html lang="fr">
<head>
	
	
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<meta name="description" content="Freshly Restaurant, your new favourite restaurant !">
	<title>Freshly Restaurant - Home</title>
	<link rel="icon" href="favicon.png">
	<link href="https://fonts.googleapis.com/css?family=Athiti:500|Merienda:400,700&display=swap" rel="stylesheet">
	<link rel="stylesheet" href="assets/css/slick.css">
	<link rel="stylesheet" href="assets/css/slick-theme.css">
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.0/css/fontawesome.min.css">
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.0/css/brands.min.css">
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.0/css/solid.min.css">
	<link rel="stylesheet" href="assets/css/style.css">
	
</head>
<body>
<header>
	<?php if($_SESSION['page']=='site'):?>
	<nav class="navbar navbar-expand-lg navbar navbar-dark bg-dark">
    		<ul>
			<li><a href="index.php" class="active">Home</a></li>
			<li><a href="index.php?page=about">About</a></li>
			<li><a href="index.php?page=menus">Menus</a></li>
			<li><a href="index.php?page=contact">Contact</a></li>
			<li><a href="index.php?page=Admin">Espace Membre</a></li>
		</ul>
	</nav>
	<?php endif?>
	<?php if(isset($_SESSION['admin'])&& $_SESSION['page']=='admin'):?>
	<nav>
		<ul>
			<li></li><a href="index.php?page=deco"><i class="fas fa-sign-out-alt"></i>Deconnexion</a></li>
			<li><a href="index.php?page=MealCategory">Gestion des catégories de plats</a></li>
			<li><a href="index.php?page=Meal">Gestion des plats</a></li>
			<li>Gestion des menus</li>
			<li><a href="index.php?page=Slider">Gestion du slider</a></li>
			
			
			<li><a href="index.php?page=opening_hour">Gestion des horaires</a></li>
			<li>Gestion des réservations</li>
			<li><a href="index.php?page=Config">Configuration</a></li>
		</ul>
	</nav>
	<?php endif; ?>
</header>

    	    
<!-- code principal de la page -->
	<?php include $template ?>

<footer>
		<div class="container">
			<div class="flex">
				<aside>
					<h4>Opening hours</h4>
					<table>
						<?php foreach($this->open as $items):?>
						<tr>
							<td><?= htmlspecialchars($items['days']);?></td>
							<td><?= htmlspecialchars($items['hours']);?></td>
						</tr>
						<?php endforeach;?>
					</table>
				</aside>
				<aside>
					<h4>Contact</h4>
					<address>
						<p><?= htmlspecialchars($this->contact['content'])?></p>
						<p><?= htmlspecialchars($this->city['content'])?></p><br>
						
						<p><?= htmlspecialchars($this->tel['content'])?></p>
					</address>
				</aside>
				<aside>
					<h4>Social networks</h4>
					<div class="reseaux">
						<a href="#" class="fab fa-facebook-f"></a>
						<a href="#" class="fab fa-instagram"></a>
						<a href="#" class="fab fa-pinterest-p"></a>
					</div>
				</aside>
			</div> <!-- end of .flex -->
			<div class="footer">
				<p><a rel="license" href="https://3wa.fr/propriete-materiel-pedagogique/"><img alt="Propriété de la 3W Academy" src="https://3wa.fr/wp-content/themes/3wa2015/img/logos/big.png"></a></p><br>
				<span>Cet exercice</span> de <a href="https://3wa.fr">3W Academy</a> est mis à disposition <a rel="license" href="https://3wa.fr/propriete-materiel-pedagogique/">pour l'usage personnel des étudiants. Pas de Rediffusion - Attribution - Pas d'Utilisation Commerciale - Pas de Modification - International</a>.<br>
				Les autorisations au-delà du champ de cette licence peuvent être obtenues auprès de <a href="mailto:contact@3wa.fr" rel="cc:morePermissions">contact@3wa.fr</a>. Les maquettes ont été réalisées par <a href="https://www.cath2nos.com">Catherine Denos</a>.
			</div> <!-- end of .footer -->
		</div> <!-- end of .container -->
	</footer>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.min.js" integrity="sha384-nsg8ua9HAw1y0W1btsyWgBklPnCUAFLuTMS2G72MMONqmOymq585AcH49TLBQObG" crossorigin="anonymous"></script>
<!-- Charger la bibliothèque de base de jQuery -->
	<script src="https://code.jquery.com/jquery-3.5.1.min.js" integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>
	<!-- Charger le script du plugin -->
	<script src="assets/js/slick.min.js"></script>
	<!-- Indiquer sur quel élément de la page on applique le plugin -->
	<script>
		$(document).ready(function () {
			$('.slider').slick({
				dots: true
			});
		});
	</script>
	
<script src=".js"></script>	
</body>
</html>	