    
        <section>
                <h1>Slider Management</h1>
                
                <button>SQLinsert into</button>
                <button>SQL update</button>
                <button>SQL delete</button>
                <button>Number of lines touched by SQL request</button>
        </section>
                
                <a href ="index.php?page=submit"><i class="fas fa-plus"></i> Create a slider</a>
            
        <table>
                <tr>
                    <td>id</td>
                    <td>src</td>
                    <td>alt</td>
                    <td>published</td>
                    <td>order</td>
                    <td>Modify</td>
                    <td>Delete</td>
                </tr>
                <!--Tu as besoin juste d'un seul foreach et c'est bon-->
                <?php foreach($sliders as $slider):?>
                <tr>
                    <td>
                    <?= htmlspecialchars($slider['id']) ?> 
                    </td>
                    <td>
                     <img class="miniatures" src="<?= htmlspecialchars($slider['src'])?>">  
                     
                    </td>
                    <td>
                    <?= htmlspecialchars($slider['alt'])?> 
                    </td>
                    <td>
                    <?= htmlspecialchars($slider['published']) ?> 
                    </td>
                    <td>
                    <?= htmlspecialchars($slider['poids'])?> 
                    </td>
                    
                    
                    <td><a class="modify" href="index.php?page=modifySlider&id=<?= htmlspecialchars($slider['id']) ?> "><i class="fas fa-pen-nib"></i></a></td>
                    
                    <!-- lien qui appelle la page trash et qui transmet l'id du slider  à supprimer  -->
                    
                    <td><a class="trash" href="index.php?page=deleteSlider&id=<?= htmlspecialchars($slider['id']) ?>"><i class="fas fa-trash-alt"></i></a>
                    </td>
                </tr>
                <?php endforeach; ?>
               
        </table>
             
        <p>Slider list classified by reverse chronological order ( <?=count($sliders)?>  in total)</p>