    
        <section>
                <h2>Slider Management</h2>
                
                <a href ="index.php?page=submit"><i class="fas fa-plus"></i> Create a slider</a>
            
        <table>
                <tr>
                    <th class="hide">id</th>
                    <th>Chemin</th>
                    <th>Descriptif</th>
                    <th>Publier ?</th>
                    <th>Ordre d'affichage</th>
                    <th>Modifier</th>
                    <th>Suprimmer</th>
                </tr>
                <!--Tu as besoin juste d'un seul foreach et c'est bon-->
                <?php foreach($sliders as $slider):?>
                <tr class="<?=(htmlspecialchars($slider['published'])==1)?'bg-ok':'bg-grey' ?>">
                    <td class="hide">
                    <?= htmlspecialchars($slider['id']) ?> 
                    </td>
                    <td>
                     <img class="miniatures" src="<?= htmlspecialchars($slider['src'])?>">  
                     
                    </td>
                    <td>
                    <?= htmlspecialchars($slider['alt'])?> 
                    </td>
                    <td>
                    <?php if(htmlspecialchars($slider['published'])==1): ?>
                    <button class="btn btn-error">Non</button>
                    <?php else : ?>
                    <button class="btn btn-success">Oui</button>
                    <?php endif ?>
                    </td>
                    <td>
                    <?= htmlspecialchars($slider['poids'])?> 
                    </td>
                    
                    
                    <td><a href="index.php?page=modifySlider&id=<?= htmlspecialchars($slider['id']) ?> "><i class="fas fa-pen-nib btn-modify"></i></a></td>
                    
                    <!-- lien qui appelle la page trash et qui transmet l'id du slider  à supprimer  -->
                    
                    <td><a class="confirmButton" data-url="index.php?page=deleteSlider&id=<?= htmlspecialchars($slider['id']) ?>"><i class="fas fa-trash-alt btn-error"></i></a>
                    </td>
                </tr>
                <?php endforeach; ?>
               
        </table>
             
        <p>Slider list classified by reverse chronological order ( <?=count($sliders)?>  in total)</p>
        </section>
        <section>
            <h2>Apperçut</h2>
        <div class="slider">
            <?php foreach($appercu as $slider):?>
            
			<div><img src="<?= htmlspecialchars($slider['src'])?>" alt="<?= htmlspecialchars($slider['alt'])?> "></div>
		
			<?php endforeach; ?>
		</div>
		</section>