    
        <section>
                <h1>Gestion des sliders</h1>
                
                
        </section>
                
                <a href ="index.php?page=submit"><i class="fas fa-plus"></i> Créer un slider</a>
            
        <table>
                <tr>
                    <td>id</td>
                    <td>Photos</td>
                    <td>titre alternatif</td>
                    <td>A publier</td>
                    <td>ordre</td>
                    <td>Modifier</td>
                    <td>Supprimer</td>
                </tr>
                <!--Tu as besoin juste d'un seul foreach et c'est bon-->
                <?php foreach($sliders as $slider):?>
                <tr>
                    <td>
                    <?= htmlspecialchars($slider['id']) ?> 
                    </td>
                    <td>
                     <img class="miniatures" src="<?= htmlspecialchars($slider['src'])?>">  
                     
                    </td>
                    <td>
                    <?= htmlspecialchars($slider['alt'])?> 
                    </td>
                    <td>
                    <?= htmlspecialchars($slider['published']) ?> 
                    </td>
                    <td>
                    <?= htmlspecialchars($slider['poids'])?> 
                    </td>
                    
                    
                    <td><a class="modify" href="index.php?page=modifySlider&id=<?= htmlspecialchars($slider['id']) ?> "><i class="fas fa-pen-nib"></i></a></td>
                    
                    <!-- lien qui appelle la page trash et qui transmet l'id du slider  à supprimer  -->
                    
                    <td><a class="trash" href="index.php?page=deleteSlider&id=<?= htmlspecialchars($slider['id']) ?>"><i class="fas fa-trash-alt"></i></a>
                    </td>
                </tr>
                <?php endforeach; ?>
               
        </table>
             
        