
        <section>
                <h1>Gestion des catégories</h1>
                
                
        </section>
                
                <a href ="index.php?page=submitCategory"><i class="fas fa-plus"></i> Créer une categorie de plats</a>
            
        <table>
                <tr>
                    <td>id</td>
                    <td>nom</td>
                    <td>S'agit-il d'un plat</td>
                    <td>description</td>
                    <td>Modifier</td>
                    <td>Supprimer</td>
                </tr>
                <!--Tu as besoin juste d'un seul foreach et c'est bon-->
                <?php foreach($mealCategory as $category):?>
                <tr>
                    <td>
                    <?= htmlspecialchars($category['id'])?> 
                    </td>
                    <td>
                    <?= htmlspecialchars($category['name'])?> 
                    </td>
                    <td>
                    <?= htmlspecialchars($category['is_dish'])?> 
                    </td>
                    <td>
                    <?= htmlspecialchars($category['description'])?> 
                    </td>
                    
                    
                    <td><a class="modify" href="index.php?page=modifyCategory&id=<?= htmlspecialchars($category['id']) ?> "><i class="fas fa-pen-nib"></i></a></td>
                    
                    <!-- lien qui appelle la page trash et qui transmet l'id de la categorie à supprimer  -->
                    
                    <td><a class="trash" href="index.php?page=deleteCategory&id=<?= htmlspecialchars($category['id']) ?>"><i class="fas fa-trash-alt"></i></a>
                    </td>
                </tr>
                <?php endforeach; ?>
               
        </table>
             
        