
        <section>
                <h1>Gestion des catégories</h1>
                
                
        </section>
                
                <a href ="index.php?page=submitCategory"><i class="fas fa-plus"></i> Créer une categorie de plats</a>
            
        <table>
                <tr>
                    <th class="hide">id</th>
                    <th>Nom</th>
                    <th>Ajouter au menu</th>
                    <th>Description</th>
                    <th>Modifier</th>
                    <th>Suppri-mer</th>
                </tr>
                <!--Tu as besoin juste d'un seul foreach et c'est bon-->
                <?php foreach($mealCategory as $category):?>
                <tr class="<?=(htmlspecialchars($category['is_dish'])==1)?'bg-ok':'bg-standar' ?>">
                    <td class="hide">
                    <?= htmlspecialchars($category['id'])?> 
                    </td>
                    <td>
                    <?= htmlspecialchars($category['name'])?> 
                    </td>
                    <td>
                    <?php if(htmlspecialchars($category['is_dish'])==1):?> 
                     <button class="btn btn-error">Non</button>
                    <?php else : ?>
                    <button class="btn btn-success">Oui</button>
                    
                    <?php endif ?>
                    </td>
                    <td>
                    <?= htmlspecialchars($category['description'])?> 
                    </td>
                    
                    
                    <td><a href="index.php?page=modifyCategory&id=<?= htmlspecialchars($category['id']) ?> "><i class="fas fa-pen-nib btn-modify"></i></a></td>
                    
                    <!-- lien qui appelle la page trash et qui transmet l'id de la categorie à supprimer  -->
                    
                    <td><a class="confirmButton" href="index.php?page=deleteCategory&id=<?= htmlspecialchars($category['id']) ?>"><i class="fas fa-trash-alt btn-error"></i></a>
                    </td>
                </tr>
                <?php endforeach; ?>
               
        </table>
             
        