<!DOCTYPE html>
<html lang="en">

<body>
	<main class="container mixitup">
		<h1>Details of our menus</h1>
		<p class="select">Choose your main course according to your menu!</p>
		<div class="filter">
			<button data-filter="all">All</button>
			<button data-filter=".meat">Meat</button>
			<button data-filter=".vegan">Vegan</button>
			<button data-filter=".fish">Fish</button>
		</div> <!-- end of .filter -->
		<div class="choice">
			<div class="mix fish">
				<figure>
					<img src="img/menus/fish-01.jpg" alt="A plate with cooked mussels">
					<figcaption><img src="img/fork-knife.svg" alt="">
						<h3>Grilled mussels</h3>
					</figcaption>
				</figure>
			</div>
			<div class="mix vegan">
				<figure>
					<img src="img/menus/vegan-03.jpg" alt="A plate with various vegan food">
					<figcaption><img src="img/fork-knife.svg" alt="">
						<h3>Mixed vegetables</h3>
					</figcaption>
				</figure>
			</div>
			<div class="mix meat">
				<figure>
					<img src="img/menus/meat-03.jpg" alt="A plate with two meat kebabs and rice">
					<figcaption><img src="img/fork-knife.svg" alt="">
						<h3>Freshly kebabs</h3>
					</figcaption>
				</figure>
			</div>
			<div class="mix fish">
				<figure>
					<img src="img/menus/fish-02.jpg" alt="A plate with shrimps and rice">
					<figcaption><img src="img/fork-knife.svg" alt="">
						<h3>Cajun shrimp</h3>
					</figcaption>
				</figure>
			</div>
			<div class="mix meat">
				<figure>
					<img src="img/menus/meat-01.jpg" alt="One big burger">
					<figcaption><img src="img/fork-knife.svg" alt="">
						<h3>Freshly burger</h3>
					</figcaption>
				</figure>
			</div>
			<div class="mix vegan">
				<figure>
					<img src="img/menus/vegan-02.jpg" alt="A plate with grilled eggplants">
					<figcaption><img src="img/fork-knife.svg" alt="">
						<h3>Grilled eggplants</h3>
					</figcaption>
				</figure>
			</div>
			<div class="mix meat">
				<figure>
					<img src="img/menus/meat-02.jpg" alt="A plate with meat cooked in tomato sauce and mushrooms">
					<figcaption><img src="img/fork-knife.svg" alt="">
						<h3>Beef stew with pasta</h3>
					</figcaption>
				</figure>
			</div>
			<div class="mix fish">
				<figure>
					<img src="img/menus/fish-03.jpg" alt="A plate with grilled salmon and vegetables">
					<figcaption><img src="img/fork-knife.svg" alt="">
						<h3>Grilled salmon</h3>
					</figcaption>
				</figure>
			</div>
			<div class="mix vegan">
				<figure>
					<img src="img/menus/vegan-01.jpg" alt="Colorfull vegetarian plate">
					<figcaption><img src="img/fork-knife.svg" alt="">
						<h3>Vegetable Jambalaya</h3>
					</figcaption>
				</figure>
			</div>
		</div> <!-- end of .choice -->
		<article>
			<h2>Deserts</h2>
			<p class="select">Here are the deserts you can choose to finish your meal (included in your menu).</p>
			<div class="choice">
				<figure>
					<img src="img/menus/desert-01.jpg" alt="A plate with a tiramisu">
					<figcaption><img src="img/fork-knife.svg" alt="">
						<h3>Tiramisu</h3>
					</figcaption>
				</figure>
				<figure>
					<img src="img/menus/desert-02.jpg" alt="Two plates with pancakes and chocolate sauce">
					<figcaption><img src="img/fork-knife.svg" alt="">
						<h3>Freshly Pancakes</h3>
					</figcaption>
				</figure>
				<figure>
					<img src="img/menus/desert-03.jpg" alt="A cup with red berries and soft white cheese">
					<figcaption><img src="img/fork-knife.svg" alt="">
						<h3>Red berries cup</h3>
					</figcaption>
				</figure>
			</div> <!-- end of .choice -->
		</article>
		<article>
			<h2>Cocktails</h2>
			<p class="select">Soft drinkgs are included, but if you want you can order one of our excellent cocktails (not included in the menu).</p>
			<div class="choice">
				<figure>
					<img src="img/menus/drink-01.jpg" alt="cocktail drink">
					<figcaption><img src="img/fork-knife.svg" alt="">
						<h3>Winter Whiskey</h3>
					</figcaption>
				</figure>
				<figure>
					<img src="img/menus/drink-02.jpg" alt="Two cocktail drinks">
					<figcaption><img src="img/fork-knife.svg" alt="">
						<h3>Paloma cocktail</h3>
					</figcaption>
				</figure>
				<figure>
					<img src="img/menus/drink-03.jpg" alt="cocktail drink">
					<figcaption><img src="img/fork-knife.svg" alt="">
						<h3>Bellini cocktail</h3>
					</figcaption>
				</figure>
			</div> <!-- end of .choice -->
		</article>
	</main>

	<!-- Charger la bibliothèque de base de jQuery -->
	<script src="https://code.jquery.com/jquery-3.5.1.min.js" integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>
	<!-- Charger le script du plugin -->
	<script src="js/mixitup.min.js"></script>
	<!-- Indiquer sur quel élément de la page on applique le plugin -->
	<script>
		var mixer = mixitup(".mixitup");
	</script>
</body>

</html>