<main>
	
	
	
	<Section>
		
		<h1>Configuration</h1>
		<form method="post">
		<p class="nom">
			<label for='nom'>Name</label>
			<input type="text" name="nom" id="nom" value="<?= (isset($config))?$config['name']:"" ?>" <?= (isset($config))?'disabled':"" ?>>
		</p>
		<p class="contenu">
			<label for='contenu'>content</label>
			<textarea id="contenu" name="contenu"><?= (isset($config))?$config['content']:""?></textarea>
		</p>
		
		<p>
		  <input type="submit" name="Ajouter"/>
		
	    <!--<input type="reset" name="Supprimer"/></p>-->
	</Section>
</main>	