
<form method="POST">
	
	<h1>Votre réservation</h1>
	
	<p>
		<label for='nbpers'>Nombre de personne</label>
		<input type="text" name="nbpers">
	</p>
	
	<p>
		<label for='date'>Date</label>
		<input type="password" name="date">
	</p>
	
	<p>
		<label for='hour'>Heure</label>
		<input type="text" name="hour">
	</p>
	
	<p>
		<label for='commment'>Commentaire</label>
		<input type="text" name="comment">
	</p>
	
	<button type="submit">GO pour la réservation</button>
	
</form>